% Vector containing the points necessary for extruding the actuator
function [vector] = ACT_extrusion(hole,height,diameter)

vector = [0          height        ;...
          0          height-10     ;...
          hole/2-10    height-10     ;...
          hole/2-10    0             ;...
          hole/2       0             ;...
          hole/2       height-10     ;...
          diameter/2   height-10     ;...
          diameter/2   height];

end


