function [Smi] = move_dx(dx)

DATA;

Smi.Car.FRONT.LEFT.CRANK_CENTEREVOLUTE(1)=Smi.Car.FRONT.LEFT.CRANK_CENTEREVOLUTE(1)+dx;
Smi.Car.FRONT.LEFT.DAMPER_CENTEREVOLUTE(1)=Smi.Car.FRONT.LEFT.DAMPER_CENTEREVOLUTE(1)+dx;
Smi.Car.FRONT.LEFT.ARB_CENTER(1)=Smi.Car.FRONT.LEFT.ARB_CENTER(1)+dx;
Smi.Car.FRONT.LEFT.CRANK_PUSHROD(1)=Smi.Car.FRONT.LEFT.CRANK_PUSHROD(1)+dx;
Smi.Car.FRONT.LEFT.CRANK_STEM(1)=Smi.Car.FRONT.LEFT.CRANK_STEM(1)+dx;
Smi.Car.FRONT.LEFT.CRANK_ARBLINK(1)=Smi.Car.FRONT.LEFT.CRANK_ARBLINK(1)+dx;
Smi.Car.FRONT.LEFT.ARBLINK_ARBBLADE(1)=Smi.Car.FRONT.LEFT.ARBLINK_ARBBLADE(1)+dx;
Smi.Car.FRONT.LEFT.UW_PUSHROD(1)=Smi.Car.FRONT.LEFT.UW_PUSHROD(1)+dx;


Calculate_Dimensions_FL;


end

